
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEIZQ = 27;
  public static final int CORCHETEDER = 28;
  public static final int MULTIPLICACION = 6;
  public static final int ELSE = 9;
  public static final int MENORIGUAL = 17;
  public static final int INT = 2;
  public static final int WHILE = 10;
  public static final int DIVISION = 5;
  public static final int SUMA = 3;
  public static final int EXPONENCIACION = 15;
  public static final int RETURN = 13;
  public static final int POTENCIA = 14;
  public static final int MAYORQUE = 18;
  public static final int IF = 8;
  public static final int ID = 31;
  public static final int IGUALDAD = 20;
  public static final int NUM = 30;
  public static final int LLAVEIZQ = 25;
  public static final int COMA = 29;
  public static final int ASIGNACION = 7;
  public static final int LLAVEDER = 26;
  public static final int DISTINTO = 21;
  public static final int EOF = 0;
  public static final int MENORQUE = 16;
  public static final int MAYORIGUAL = 19;
  public static final int PARENIZQ = 22;
  public static final int error = 1;
  public static final int PARENDER = 24;
  public static final int PUNTOCOMA = 23;
  public static final int FOR = 11;
  public static final int VOID = 12;
  public static final int RESTA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "ASIGNACION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "VOID",
  "RETURN",
  "POTENCIA",
  "EXPONENCIACION",
  "MENORQUE",
  "MENORIGUAL",
  "MAYORQUE",
  "MAYORIGUAL",
  "IGUALDAD",
  "DISTINTO",
  "PARENIZQ",
  "PUNTOCOMA",
  "PARENDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "CORCHETEIZQ",
  "CORCHETEDER",
  "COMA",
  "NUM",
  "ID"
  };
}

